version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    volumes:
      - "./docker-compose/postgres:/docker-entrypoint-initdb.d:ro"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  dovecot:
    build: "./dovecot"
    volumes:
      - "./docker-compose/dovecot:/etc/dovecot:ro"
    environment: {}
  roundcube:
    image: "roundcube/roundcubemail:latest"
    ports:
      - target: 80
        published: 8080
        protocol: "tcp"
        mode: "host"
    environment:
      ROUNDCUBEMAIL_DB_TYPE: "pgsql"
      ROUNDCUBEMAIL_DB_HOST: "postgres"
      ROUNDCUBEMAIL_DB_PORT: "5432"
      ROUNDCUBEMAIL_DB_USER: "postgres"
      ROUNDCUBEMAIL_DB_PASSWORD: "postgres"
      ROUNDCUBEMAIL_DB_NAME: "roundcube"
      ROUNDCUBEMAIL_SKIN: "elastic"
      ROUNDCUBEMAIL_DEFAULT_HOST: "dovecot"
      ROUNDCUBEMAIL_SMTP_SERVER: "tls://mail.example.org"
    depends_on:
      - "postgres"
      - "dovecot"
