version: "3.9"
services:
  roundcube:
    build: "./roundcube/"
    ports:
      - target: 80
        published: 8080
        protocol: "tcp"
        mode: "host"
    volumes:
      - "./roundcube/nginx:/etc/nginx"
