version: "3.9"
services:
  postgesql:
    image: "postgres:latest"
  roundcube:
    image: "roundcube/roundcubemail:latest"
    ports:
      - target: 80
        published: 8080
        protocol: "tcp"
        mode: "host"
  opensmtpd:
    build: "./opensmtpd"
    ports:
      - target: 25
        published: 2525
        protocol: "tcp"
        mode: "host"
  dovecot:
    build: "./dovecot"
